source/WebView/Controllers/MaterialMastMaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.EntityClient;
using System.Data.EntityModel;
using Oracle.DataAccess.Client;
using System.Data.Objects;
using System.Data.Common;
using System.Data;
using WebView.Models;
using WebView.Library;
using System.IO;
using PagedList;

namespace WebView.Controllers
{
    public class MaterialMastMaintenanceController : Controller
    {
        //
        // GET: /MaterialMastMaintenance/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchKey,string searchUOM, int? page)
        {
            WebView.WebService._base myWebService;
            myWebService = new WebService._base();
            //System.Diagnostics.Debug.WriteLine("Controller 1 :" + "  search key : " + searchKey + " search UOM : " + searchUOM);
            WebService._base.OSPMaterialMasterMaintenance MatMastM = new WebService._base.OSPMaterialMasterMaintenance();

            MatMastM = myWebService.GetOSPMaterialMasterMaintenance(0, 100000, searchKey, searchUOM);
                ViewBag.searchKey = searchKey;
                ViewBag.searchUOM2 = searchUOM;

            string input = "\\\\adsvr";
            //string input = "\\\\server\\d$\\x\\y\\z\\AAA";
            string output = String.Format("http:{0}", input.Replace("\\d$\\x\\y", String.Empty).Replace("\\", "/"));

            ViewBag.output = output;


            List<SelectListItem> listMatUOM = new List<SelectListItem>();
            using (Entities ctxData = new Entities())
            {
                var query = (from p in ctxData.WV_MAT_MAST
                             orderby p.MAT_UOM
                             select new { p.MAT_UOM, });

                listMatUOM.Add(new SelectListItem() { Text = "", Value = "Select" });

                foreach (var a in query.Distinct())
                {
                    if (a.MAT_UOM != null)
                    {
                        listMatUOM.Add(new SelectListItem() { Text = a.MAT_UOM, Value = a.MAT_UOM });
                    }
                }

                ViewBag.MatUOM = listMatUOM;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(MatMastM.MatMastMaintenanceList.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult NewMaterialMastMaintenance()
        {
            List<SelectListItem> listMatUOM = new List<SelectListItem>();
            using (Entities ctxData = new Entities())
            {
                var query = (from p in ctxData.WV_MAT_MAST 
                             orderby p.MAT_UOM descending 
                            select new {p.MAT_UOM  });

                foreach (var a in query.Distinct())
                {
                    if (a.MAT_UOM != null)
                    {
                        listMatUOM.Add(new SelectListItem() { Text = a.MAT_UOM, Value = a.MAT_UOM });
                    }
                }

                ViewBag.MatUOM = listMatUOM;
            }

            List<SelectListItem> listMatMatCat = new List<SelectListItem>();
            using (Entities ctxData = new Entities())
            {
                var query = from p in ctxData.WV_MAT_MAST
                            select new { Text = p.MAT_CAT, Value = p.MAT_CAT };

                foreach (var a in query.Distinct())
                {
                    listMatMatCat.Add(new SelectListItem() { Text = a.Text, Value = a.Value.ToString() });
                }

                ViewBag.MatCat = listMatMatCat;
            }
            return View();
        }

        [HttpPost]
        public ActionResult NewMaterialMastMaintenance(MaterialMastMaintenanceModel m)
        {
            bool success = true;
            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            bool selected = false;

            WebService._base.MaterialMasterMaintenance newMatMastM = new WebService._base.MaterialMasterMaintenance();

            System.Diagnostics.Debug.WriteLine("base :2  Mat Name [" + newMatMastM.MAT_NAME + "]   Mat UOM  [" + newMatMastM.MAT_UOM + "]   Mat Price [" + newMatMastM.MAT_PRICE + "] Mat Cat [" + newMatMastM.MAT_CAT + "]  Record Type [" + newMatMastM.RECORD_TYPE + "]  Tras Type [" + newMatMastM.TRANS_TYPE + "] ");
           
            newMatMastM.MAT_NAME = m.MatName;
            newMatMastM.MAT_UOM = m.MatUOM;
            newMatMastM.MAT_PRICE = m.MatPrice.ToString();
            newMatMastM.MAT_CAT = m.MatCat;
            newMatMastM.RECORD_TYPE = m.RecordType;
            newMatMastM.TRANS_TYPE = m.TransType;
            success = myWebService.AddMatMastMaintenance(newMatMastM);
            selected = true;

            //if (ModelState.IsValid && selected)
            //{
            if (success == true)
            {
                return RedirectToAction("NewSave");
            }
            else
            {
                return RedirectToAction("NewSaveFail"); // store to db failed.
            }
            //}

            //return View(m);
        }

        public ActionResult NewSave()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetDetails(string id)
        {
            string fileListStr = "";
            string datauom = "";
            string dataCat = "";

            using (Entities ctxData = new Entities())
            {
                var query = (from q in ctxData.WV_MAT_MAST
                             where q.MAT_ID == id
                             select q).Single();

                var queryUOM = (from q in ctxData.WV_MAT_MAST
                                select new { q.MAT_UOM, q.MAT_CAT });

                foreach (var a in queryUOM.Distinct())
                {
                    datauom = datauom + a.MAT_UOM + ":";
                }
                foreach (var a in queryUOM.Distinct())
                {
                    dataCat = dataCat + a.MAT_CAT + ":";
                }
                
                System.Diagnostics.Debug.WriteLine("OUM :" + datauom + "  Cat :" + dataCat);
                return Json(new
                {
                    Success = true,
                    MatId = id,
                    MatName = query.MAT_NAME,
                    MatUOM = query.MAT_UOM,
                    MatPrice = query.MAT_PRICE,
                    MatCat = query.MAT_CAT,
                    RecType = query.RECORD_TYPE,
                    TransType = query.TRANS_TYPE, 
                    UOM = datauom,
                    Cat = dataCat,

                    files_list = new
                    {
                        files = fileListStr
                    }
                }, JsonRequestBehavior.AllowGet); //
            }
        }

        [HttpPost]
        public ActionResult DeleteData(string targetMatId)
        {
            bool success;

            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            success = myWebService.DeleteMatMastMaintenance(targetMatId);

            return Json(new
            {
                Success = success
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateData(string MatIdVal, string txtMatName, string txtMatUOM, string txtMatPrice, string txtMatCat, string txtRecType, string txtTransType)
        {
            bool success = true;

            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            WebService._base.MaterialMasterMaintenance newMatMast = new WebService._base.MaterialMasterMaintenance();
            newMatMast.MAT_NAME = txtMatName;
            newMatMast.MAT_UOM = txtMatUOM;
            newMatMast.MAT_PRICE = txtMatPrice;
            newMatMast.MAT_CAT = txtMatCat;
            newMatMast.RECORD_TYPE = txtRecType;
            newMatMast.TRANS_TYPE = txtTransType;          
            success = myWebService.UpdateMatMastMaintenance(newMatMast, MatIdVal);

            return Json(new
            {
                Success = success
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

source/WebView/Views/MaterialMastMaintenance/List.cshtml
@model PagedList.IPagedList<WebView.WebService._base.MaterialMasterMaintenance>
@{
    ViewBag.Title = "List";
}

<script type="text/javascript">

    function GetDetailsCallBack(data) {
        document.getElementById("divDetails").style.display = "block";

        SetText("txtMatId", data.MatId);
        SetElement("txtMatName", data.MatName);
        SetElement("txtMatUOM", data.MatUOM);
        SetElement("txtMatPrice", data.MatPrice);
        SetElement("txtMatCat", data.MatCat);
        SetElement("txtRecType", data.RecType);
        SetElement("txtTransType", data.TransType);       
        SetElement("MatIdVal", data.MatId);
        document.getElementById("targetMatId").value = data.MatId;

        document.getElementById("btnClose").disabled = false;
    }

    function SaveUpdateCallBack(data) {
        document.getElementById("txtMatName").readOnly = true;
        document.getElementById("txtMatUOM").readOnly = true;
        document.getElementById("txtMatPrice").readOnly = true;
        document.getElementById("txtMatCat").readOnly = true;
        document.getElementById("txtRecType").readOnly = true;
        document.getElementById("txtTransType").readOnly = true;       
        document.getElementById("btnSave").disabled = true;

        if (data.Success == true) {
            alert("Successfully Updated.");
            document.getElementById("divDetails").style.display = "none";
            document.getElementById("btnSave").disabled = false;
            window.location.reload();
        }
    }

    jQuery(document).ready(function ($) {

        $("#rounded-corner tbody tr").bind("click", function () {
            var t = $(this).find("#gid").text();
            //var cmsg = confirm(t);

            $("#divDetails").dialog("open");

            $.ajax({
                url: '@Url.Action("GetDetails", "MaterialMastMaintenance")',
                type: "POST",
                dataType: "html",
                data: {
                    "id": t,
                    "random": Math.random()
                },
                beforeSend: function () { },
                success: function (data) {
                    var res = jQuery.parseJSON(data);

                    GetDetailsCallBack(res);


                    UOMList = res.UOM.split(":");
//                    alert(res.UOM);
                    var dataListName = "<option selected value='" + res.MatUOM + "'>" + res.MatUOM + "</option>";

                    for (i = 1; i < UOMList.length; i++) {
                        if (UOMList[i] != "") {

                            dataListName += "<option value='" + UOMList[i] + "'>" + UOMList[i] + "</option>";
                        }
                    }
                    $("#txtMatUOM").html(dataListName);

                    CatList = res.Cat.split(":");
                    //                    alert(res.UOM);
                    var dataListName = "<option selected value='" + res.MatCat + "'>" + res.MatCat + "</option>";

//                    for (i = 1; i < CatList.length; i++) {
//                        if (CatList[i] != "") {

//                            
//                        }
//                    }
                    dataListName += "<option value='C1'> C1 </option>";
                    $("#txtMatCat").html(dataListName);
                    //                    var itemsMatUOM = "<option value='" + res.MatUOM + "'>" + res.MatUOM + "</option>";
                    //                    $("#txtMatUOM").html(itemsMatUOM);

                    //                    var itemsMatCat = "<option value='" + res.MatCat + "'>" + res.MatCat + "</option>";
                    //                    $("#txtMatCat").html(itemsMatCat);

                }
            });
        });

        $('#btnSearch').click(function () {
            window.location = "List?searchKey=" + document.getElementById("searchKey").value + "&searchUOM=" + document.getElementById("searchUOM").value; //Where List is the function in the controller.
        });

        var close = function () {
            $(this).dialog("close");
        }

        $("#divDetails").dialog({
            autoOpen: false,
            height: 290,
            width: 900,
            modal: true,
            buttons: {
            },
            close: function () {
                //allFields.val("").removeClass("ui-state-error");
            }
        });

        $(function () {
            $('#btnClose').click(function () {
                $("#divDetails").dialog("close");
            });

            $('#btnNewJob').click(function () {
                window.location = "NewMaterialMastMaintenance";
            });

            $("#btnNewJob").button();
            $("#btnSearch").button();
            $("#btnClose").button();
            $("#btnDelete").button();
            $("#btnSave").button();

            $('#btnDelete').click(function () {
                var cmsg = confirm('Are you sure you want to Delete?');
                if (cmsg != 0) {
                    $.ajax({
                        url: "/MaterialMastMaintenance/DeleteData",
                        type: "POST",
                        dataType: "html",
                        data: {
                            "targetMatId": document.getElementById("targetMatId").value,
                            "random": Math.random()
                        },
                        beforeSend: function () { },
                        success: function (data) {
                            var res = jQuery.parseJSON(data);

                            if (res.Success == true) {
                                alert("Deleted");
                                window.location.reload();
                            }
                            else {
                                alert("Delete failed.");
                            }
                        }
                    });
                }
            });
        });
    });

    function ShowIt() {
        document.getElementById("divLoading").style.visibility = "visible";
    }

    function HideIt() {
        document.getElementById("divLoading").style.visibility = "hidden";
    }

</script>

<br />
<h2>Material Master Maintenance List</h2>
    <div>
        <table style="width:850px;">
            <tr>
                <td style="width:350px;">Mat Name : <input type="text" id="searchKey" name="searchKey"  value="@ViewBag.searchKey"/></td>
                 <td style="width:40px;">  UOM : </td ><td >   @Html.DropDownList("searchUOM", (IEnumerable<SelectListItem>)ViewBag.MatUOM, new { style = "width:150px" })</td> 
                 <td><input type="button" value="Search" id="btnSearch" /></td>
                <td style="width:200px;"></td>
                <td style="text-align:right"><input type="button" value="Add New" id="btnNewJob" /></td>
            </tr>
        </table>
    </div><br />
<div style="height:650px">
    @if (Model.Count() > 0)
    {
        <table id="rounded-corner" summary="MaterialMastMaintenance List" width="850px">
            <thead>
                <tr>
                    <th scope="col">Material ID</th>
                    <th scope="col">Material Name</th>
                    <th scope="col">Material UOM</th>
                    <th scope="col" >Material Price</th>
                    <th scope="col" >Material Category</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var res in Model)
            {
                <tr class="odd">
                    <td id="gid">@res.MAT_ID</td>
                    <td>@res.MAT_NAME</td>
                    <td>@res.MAT_UOM</td>
                    <td>@res.MAT_PRICE</td>
                    <td>@res.MAT_CAT</td>
                </tr>    
            }
            </tbody>
        </table>
        <div>
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            of @Model.PageCount

            
            &nbsp;
            @if (Model.HasPreviousPage)
            {
                @Html.ActionLink("<<", "List", new { searchKey = ViewBag.searchKey, searchUOM = ViewBag.searchUOM2, page = 1 })
                @Html.Raw("&nbsp;");
                @Html.ActionLink("< Prev", "List", new { searchKey = ViewBag.searchKey, searchUOM = ViewBag.searchUOM2, page = Model.PageNumber - 1 })
            }
            else
            {

            }
            &nbsp;
            @if (Model.HasNextPage)
            {
                @Html.ActionLink("Next >", "List", new { searchKey = ViewBag.searchKey, searchUOM = ViewBag.searchUOM2, page = Model.PageNumber + 1 })
                @Html.Raw("&nbsp;");
                @Html.ActionLink(">>", "List", new { searchKey = ViewBag.searchKey, searchUOM = ViewBag.searchUOM2, page = Model.PageCount })
            }
            else
            {

            }<br/><b> Total @Model.TotalItemCount records</b>
        </div>
    }
    else
    {
        @:<br /><span style="font-size:12px;">No record found.</span> 
    }
    <br />
    <div id="divLoading" style="visibility:hidden"><img src="@Url.Content("~/Content/images/rel_interstitial_loading.gif")" alt="loading..." /></div>
    <div id="divResultText"></div>
    <br />
    <div id="divDetails" title="Details" style="padding-left:40px; padding-top:30px;">  
    <span style="font-size:12px">Material ID #</span><span id="txtMatId" style="font-weight:bold; color:Blue"></span>
        <input type="hidden" id="targetMatId" value="" />
        @using (Ajax.BeginForm("UpdateData", new AjaxOptions()
        {
            OnBegin = "ShowIt",
            OnComplete = "HideIt",
            OnSuccess = "SaveUpdateCallBack"
        }))
        {
        <div id="list-details">
           <input type="hidden" id="MatIdVal" name="MatIdVal" />
            <table width="800px">
                <tr>
                    <td style="width:150px; background-color:#e8eef4">Material Name</td>
                    <td><input type="text" id="txtMatName" name="txtMatName" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>
                     
                    <td style="width:150px; background-color:#e8eef4">Record Type</td>
                    <td><input type="text" id="txtRecType" name="txtRecType" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                   
                </tr>
              <tr>
                    <td style="width:150px; background-color:#e8eef4">Material UOM</td>
                    
                    <td><select id="txtMatUOM" name="txtMatUOM">
                    </select></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>
                    
                     <td style="width:150px; background-color:#e8eef4">Trans Type</td>
                    <td><input type="text" id="txtTransType" name="txtTransType" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                     
                </tr>
                <tr> 
                    <td style="width:150px; background-color:#e8eef4">Material Price</td>
                    <td><input type="text" id="txtMatPrice" name="txtMatPrice" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>       
                 </tr>
                <tr>
                    <td style="width:150px; background-color:#e8eef4">Material Category</td>
                    <td><select id="txtMatCat" name="txtMatCat">
                    </select></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                                
                </tr>
            </table>
            <br />
            <div style="height:30px; margin-top:10px; margin-left:10px;">
                <input type="button" value="Delete" id="btnDelete" style="height:30px;width:80px; vertical-align:top;" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="Save" id="btnSave" style="height:30px;width:80px; vertical-align:top;" />
                <input type="button" value="Cancel" id="btnClose" style="height:30px;width:80px;" />
            </div>
        </div>
        }
        <br />
        <br />
    </div>
</div>
    

source/WebView/Views/MaterialMastMaintenance/NewMaterialMastMaintenance.cshtml
@model WebView.Models.MaterialMastMaintenanceModel

@{
    ViewBag.Title = "MaterialMastMaintenance";
}
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(function () {
            $("#btnSave").button();
        });
    });
</script>
<br />
<h2>New Material Master Maintenance</h2>
@using (Html.BeginForm("NewMaterialMastMaintenance", "MaterialMastMaintenance", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "Error. Please correct the errors and try again.");
    <table width="450px" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td>Material Name</td>
            <td>
                @Html.TextBoxFor(m => m.MatName, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.MatName)
            </td>
        </tr>
        <tr>
            <td>Material UOM</td>
            <td>
                @*@Html.DropDownListFor(m => m.MatUOM, (IEnumerable<SelectListItem>)ViewBag.MatUOM, new { style = "width:200px;" })*@
                @Html.DropDownListFor(m => m.MatUOM, (IEnumerable<SelectListItem>)ViewBag.MatUOM, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.MatUOM )
            </td>
        </tr>
        <tr>
            <td>Material Price</td>
            <td>
                @Html.TextBoxFor(m => m.MatPrice, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.MatPrice)
            </td>
        </tr>
         <tr>
            <td>Material Category</td>
            <td>
                @*@Html.DropDownListFor(m => m.MatCat, (IEnumerable<SelectListItem>)ViewBag.MatCat, new { style = "width:200px;" })*@
                @Html.DropDownListFor(m => m.MatCat, (IEnumerable<SelectListItem>)ViewBag.MatCat, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.MatCat )
            </td>
        </tr>
         <tr>
            <td>Record Type</td>
            <td>
                @Html.TextBoxFor(m => m.RecordType, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.RecordType)
            </td>
        </tr>
         <tr>
            <td>Trans Type</td>
            <td>
                @Html.TextBoxFor(m => m.TransType, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.TransType)
            </td>
        </tr>
    </table>
    <p>
        <input type="submit" value="Save" id="btnSave" />
    </p>                                                                                   
}

source/WebView/Views/MaterialMastMaintenance/NewSave.cshtml
@{
    ViewBag.Title = "NewSave";
}

<h2>Status</h2>
<div style="height:400px">
New Material Master Maintenance has been created.
</div>