source/WebView/Controllers/PUMMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.EntityClient;
using System.Data.EntityModel;
using Oracle.DataAccess.Client;
using System.Data.Objects;
using System.Data.Common;
using System.Data;
using WebView.Models;
using WebView.Library;
using System.IO;
using PagedList;

namespace WebView.Controllers
{

    public class PUMMController : Controller
    {
       
        // GET: /PUMM/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PUMM_List(string searchKey, int? page)
        {
            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            WebService._base.OSPPUMM PUMM = new WebService._base.OSPPUMM();

            if (searchKey != null)
            {
                if (searchKey.Equals(""))
                    PUMM = myWebService.GetOSPPUMM(0, 1000, null);
                else
                {
                    PUMM = myWebService.GetOSPPUMM(0, 1000, searchKey);
                    ViewBag.searchKey = searchKey;
                }
            }
            else
            {
                PUMM = myWebService.GetOSPPUMM(0, 1000, null);
                ViewBag.searchKey = "";
            }
            
            ViewData["data7"] = PUMM.PUMMList;

            string input = "\\\\adsvr";
            //string input = "\\\\server\\d$\\x\\y\\z\\AAA";
            string output = String.Format("http:{0}", input.Replace("\\d$\\x\\y", String.Empty).Replace("\\", "/"));

            ViewBag.output = output;

            //return View();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(PUMM.PUMMList.ToPagedList(pageNumber, pageSize));
        }
    
        public ActionResult PUMM_NewJob()
        {           
            return View();
        }

        [HttpPost]
        public ActionResult PUMM_NewJob(PUMM_NewJobModel model)
        {
            bool success = true;
            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            bool selected = false;          
           
                WebService._base.PUMM PUMM_newjob = new WebService._base.PUMM();              
                PUMM_newjob.PU_ID = model.x_PU_ID;
                PUMM_newjob.PU_DESC = model.x_PU_DESC ;             
                PUMM_newjob.MAT_ID = model.x_MAT_ID;
                PUMM_newjob.MAT_NAME = model.x_MAT_NAME;
                PUMM_newjob.MAT_QTY = model.x_MAT_QTY;             
                success = myWebService.AddPUMM (PUMM_newjob);

                selected = true;
           
            if (ModelState.IsValid && selected)
            {
                if(success == true) 
                    return RedirectToAction("PUMM_NewSave");
                else
                    return RedirectToAction("NewSaveFail"); // store to db failed.
            }           

            return View(model);
        }    

        public ActionResult PUMM_NewSave()
        {
            return View();
        }

        public ActionResult GetDetails_PUMM(string id)
        {
            using (Entities ctxData = new Entities())
            {
                var query = (from p in ctxData.WV_PUMM_MAST
                             where p.PU_ID == id
                             select p).Single();

                return Json(new
                {    
                   
                    Success = true,
                    x_PU_ID = id,                    
                    x_PU_DESC = query.PU_DESC,
                    x_MAT_ID = query.MAT_ID,
                    x_MAT_NAME = query.MAT_NAME,
                    x_MAT_QTY = query.MAT_QTY,
                
                }, JsonRequestBehavior.AllowGet); //
            }
        }

        public ActionResult UpdateData_PUMM(string txtPU_ID, string txtPU_DESC, string txtMAT_ID, string txtMAT_NAME, string txtMAT_QTY)
        {
            bool success = true;

            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            WebService._base.PUMM PUMM_newjob = new WebService._base.PUMM();
            PUMM_newjob.PU_ID = txtPU_ID;
            PUMM_newjob.PU_DESC = txtPU_DESC;
            PUMM_newjob.MAT_ID = txtMAT_ID;
            PUMM_newjob.MAT_NAME = txtMAT_NAME;
            PUMM_newjob.MAT_QTY = txtMAT_QTY;            
            success = myWebService.UpdatePUMM(PUMM_newjob, txtPU_ID);

            return Json(new
            {
                Success = success
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteData_PUMM(string targetPUMM)
        {
            bool success;

            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            success = myWebService.Delete_PUMM(targetPUMM);

            return Json(new
            {
                Success = success
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

source/WebView/Views/PUMM/PUMM_List.cshtml
@model PagedList.IPagedList<WebView.WebService._base.PUMM>
@{
    ViewBag.Title = "PUMM_List";
}
<script type="text/javascript">

    function GetDetailsCallBack(data) {
        document.getElementById("divDetails").style.display = "block";

        SetElement("txtPU_ID", data.x_PU_ID);
        SetElement("txtPU_ID1", data.x_PU_ID);
        SetElement("txtPU_DESC", data.x_PU_DESC);
        SetElement("txtMAT_ID", data.x_MAT_ID);
        SetElement("txtMAT_NAME", data.x_MAT_NAME);
        SetElement("txtMAT_QTY", data.x_MAT_QTY);
        SetText("txtPU_ID", data.x_PU_ID);

        document.getElementById("targetPUMM").value = data.x_PU_ID;
        document.getElementById("btnClose").disabled = false;
                
    }

    function SaveUpdateCallBack(data) {
        document.getElementById("txtPU_ID1").readOnly = true;
        document.getElementById("txtPU_DESC").readOnly = true;
        document.getElementById("txtMAT_ID").readOnly = true;
        document.getElementById("txtMAT_NAME").readOnly = true;
        document.getElementById("txtMAT_QTY").readOnly = true;
        //document.getElementById("btnSave").disabled = true;

        if (data.Success == true) {
            alert("Successfully Updated.");
            document.getElementById("divDetails").style.display = "none";
            window.location.reload();
        }
    }

    jQuery(document).ready(function ($) {
        $("#rounded-corner tbody tr").bind("click", function () {
            var t = $(this).find("#gid").text();

            $("#divDetails").dialog("open");

            $.ajax({
                url: '@Url.Action("GetDetails_PUMM", "PUMM")',
                type: "POST",
                dataType: "html",
                data: {
                    "id": t,
                    "random": Math.random()
                },
                beforeSend: function () { },
                success: function (data) {
                    var res = jQuery.parseJSON(data);

                    GetDetailsCallBack(res);
                    //$.msgBox("Please la."); 
                }
            });
        });

        var close = function () {
            $(this).dialog("close");
        }

        $("#divDetails").dialog({
            autoOpen: false,
            height: 230,
            width: 700,
            modal: true,
            buttons: {
            },
            close: function () {
                //allFields.val("").removeClass("ui-state-error");
            }
        });

        $(function () {
            $('#btnSearch').click(function () {
                window.location = "PUMM_List?searchKey=" + document.getElementById("searchKey").value; //Where List is the function in the controller.
            });

            $('#searchKey').change(function () {
                window.location = "PUMM_List?searchKey=" + document.getElementById("searchKey").value; //Where List is the function in the controller.
            });

            $('#btnClose').click(function () {
                $("#divDetails").dialog("close");
            });

            $('#btnNewJob').click(function () {
                window.location = "PUMM_NewJob";
            });

            $("#btnNewJob").button();
            $("#btnSearch").button();
            $("#btnClose").button();
            $("#btnDelete").button();
            $("#btnSave").button();

            $('#btnDelete').click(function () {
                var cmsg = confirm('Are you sure you want to Delete?');
                if (cmsg != 0) {
                    $.ajax({
                        url: "/PUMM/DeleteData_PUMM",
                        type: "POST",
                        dataType: "html",
                        data: {
                            "targetPUMM": document.getElementById("targetPUMM").value,
                            "random": Math.random()
                        },
                        beforeSend: function () { },
                        success: function (data) {
                            var res = jQuery.parseJSON(data);

                            if (res.Success == true) {
                                alert("Deleted");
                                window.location.reload();
                            }
                            else {
                                alert("Delete failed.");
                            }
                        }
                    });
                }
            });


        });
    });


    function ShowIt() {
        document.getElementById("divLoading").style.visibility = "visible";
    }

    function HideIt() {
        document.getElementById("divLoading").style.visibility = "hidden";
    }

   
</script>

<br />
<h2>Plant Unit Material Maintenance(Copper) List</h2>
<div style="height:650px">
    <div>
        <table style="width:850px;">
            <tr>
                <td style="width:200px;"><input type="text" id="searchKey" name="searchKey"  value="@ViewBag.searchKey"/></td>
                <td><input type="button" value="Search" id="btnSearch" /></td>
                <td style="text-align:right"><input type="button" value="Add New" id="btnNewJob" /></td>
            </tr>
        </table>
    </div><br />
    @if (Model.Count() > 0)
    {
    <table id="rounded-corner" summary="Plant Unit Material List" width="850px">
        <thead>
            <tr>                
                <th scope="col" style="width:100px">ID</th>
                <th scope="col" style="width:100px">DESCRIPTION</th>
                <th scope="col" style="width:100px">MATERIAL ID</th>
                <th scope="col" style="width:100px">MATERIAL NAME</th>
                <th scope="col" style="width:100px">MATERIAL QTY</th>             
            </tr>
        </thead>
        <tbody>
        @foreach (var res in Model)
        {
            <tr class="odd">               
                <td id="gid">@res.PU_ID</td>
                <td>@res.PU_DESC</td>
                <td>@res.MAT_ID</td>
                <td>@res.MAT_NAME</td>
                <td>@res.MAT_QTY</td>            
                @*<td>@Ajax.ActionLink("View", "GetDetails_PUMM", new { id = res.PU_ID }, new AjaxOptions
               {
                   HttpMethod = "POST",
                   OnBegin = "ShowIt",
                   OnComplete = "HideIt",
                   UpdateTargetId = "divResultText",
                   OnSuccess = "GetDetailsCallBack"
               })</td>*@
            </tr>    
        }
        </tbody>
    </table>
    <div> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of @Model.PageCount
        &nbsp;
        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("<<", "List", new { searchKey = "", page = 1 })
            @Html.Raw("&nbsp;");
            @Html.ActionLink("< Prev", "List", new { searchKey = "", page = Model.PageNumber - 1 })
        }
        else
        {

        }
        &nbsp;
        @if (Model.HasNextPage)
        {
            @Html.ActionLink("Next >", "List", new { searchKey = "", page = Model.PageNumber + 1 })
            @Html.Raw("&nbsp;");
            @Html.ActionLink(">>", "List", new { searchKey = "", page = Model.PageCount })
        }
        else
        {

        }
    </div>     
    }
    else
    {
        @:<br /><span style="font-size:12px;">No record found.</span> 
    }     
    <br />
    <div id="divLoading" style="visibility:hidden"><img src="@Url.Content("~/Content/images/rel_interstitial_loading.gif")" alt="loading..." /></div>
    <div id="divResultText"></div>
    <br />
    <div id="divDetails" title="Details" style="padding-left:40px; padding-top:30px;">
         <input type="hidden" id="txtPU_ID" value="" />
        <input type="hidden" id="targetPUMM" value="" />
        @using (Ajax.BeginForm("UpdateData_PUMM", new AjaxOptions()
        {
            OnBegin = "ShowIt",
            OnComplete = "HideIt",
            OnSuccess = "SaveUpdateCallBack"
        }))
        {
        <div id="list-details">
            <table width="600px">
                <tr>
                    <td style="width:100px; background-color:#e8eef4">ID</td>
                    <td><input type="text" id="txtPU_ID1" name="txtPU_ID" readonly /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>
                    <td style="width:100px;background-color:#e8eef4">Description</td>
                    <td><input type="text" id="txtPU_DESC" name="txtPU_DESC" /></td>
                </tr>
                <tr>
                    <td style="width:100px; background-color:#e8eef4">Material ID</td>
                    <td><input type="text" id="txtMAT_ID" name="txtMAT_ID" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>
                    <td style="width:100px;background-color:#e8eef4">Material Name</td>
                    <td><input type="text" id="txtMAT_NAME" name="txtMAT_NAME" /></td>
                </tr>
                <tr>
                    <td style="width:100px; background-color:#e8eef4">Material Qty</td>
                    <td><input type="text" id="txtMAT_QTY" name="txtMAT_QTY" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                   
                </tr>                  
                </table>
            <div style="height:30px; margin-top:10px; margin-left:10px;">
                <input type="button" value="Delete" id="btnDelete" style="height:30px;width:80px; vertical-align:top;" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="Save" id="btnSave" style="height:30px;width:80px; vertical-align:top;" />
                <input type="button" value="Cancel" id="btnClose" style="height:30px;width:80px;" />
            </div>
        </div>
        }
    </div>
</div>
    

source/WebView/Views/PUMM/PUMM_NewJob.cshtml
@model WebView.Models.PUMM_NewJobModel
           
@{
    ViewBag.Title = "PUMM_NewJob";
}
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(function () {
            $("#btnSave").button();
        });
    });
</script>
<br />
<h2>New Plant Unit Material</h2>
@using (Html.BeginForm("PUMM_NewJob", "PUMM", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "Error. Please correct the errors and try again.");
    <table width="600px" cellpadding="0" cellspacing="0" border="0">      
        <tr>
            <td>PU ID</td>
            <td>
             @Html.TextBoxFor(m => m.x_PU_ID, new { style = "width:200px;" })
             @Html.ValidationMessageFor(m => m.x_PU_ID)
            </td>
        </tr>
        <tr>
            <td>PU Description</td>
            <td>
             @Html.TextBoxFor(m => m.x_PU_DESC, new { style = "width:200px;" })
             @Html.ValidationMessageFor(m => m.x_PU_DESC)
            </td>
        </tr>
        <tr>
            <td>Material ID</td>
            <td>
             @Html.TextBoxFor(m => m.x_MAT_ID, new { style = "width:200px;" })
             @Html.ValidationMessageFor(m => m.x_MAT_ID)
            </td>
        </tr>
         <tr>
            <td>Material Name</td>
            <td>
             @Html.TextBoxFor(m => m.x_MAT_NAME, new { style = "width:200px;" })
             @Html.ValidationMessageFor(m => m.x_MAT_NAME)
            </td>
        </tr>
         <tr>
            <td>Material Qty</td>
            <td>
            @Html.TextBoxFor(m => m.x_MAT_QTY, new { style = "width:200px;" })
            @Html.ValidationMessageFor(m => m.x_MAT_QTY)
            </td>
        </tr>           
    </table>
    <p>
        <input type="submit" value="Save" id="btnSave" />
    </p>    
}

source/WebView/Views/PUMM/PUMM_NewSave.cshtml
@{
    ViewBag.Title = "PUMM_NewSave";
}

<h2>Status</h2>
<div style="height:400px">
New Plant Unit Material has been created.
</div>