source/WebView/Controllers/PTTMaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.EntityClient;
using System.Data.EntityModel;
using Oracle.DataAccess.Client;
using System.Data.Objects;
using System.Data.Common;
using System.Data;
using WebView.Models;
using WebView.Library;
using System.IO;
using PagedList;

namespace WebView.Controllers
{
    public class PTTMaintenanceController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchKey, int? page)
        {
            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            WebService._base.OSPPTTMaintenance PTTMain = new WebService._base.OSPPTTMaintenance();

            if (searchKey != null)
            {
                if (searchKey.Equals(""))
                    PTTMain = myWebService.GetOSPPTTMaintenance(0, 100, null);
                else
                {
                    PTTMain = myWebService.GetOSPPTTMaintenance(0, 100, searchKey);
                    ViewBag.searchKey = searchKey;
                }
            }
            else
            {
                PTTMain = myWebService.GetOSPPTTMaintenance(0, 100, null);
                ViewBag.searchKey = "";
            }         

            ViewData["data7"] = PTTMain.PTTMaintenanceList;

            List<SelectListItem> list2 = new List<SelectListItem>();
            using (Entities ctxData = new Entities())
            {
                
                var sStateName = (from d in ctxData.WV_STATE_MAST 
                            select d);

                list2.Add(new SelectListItem() { Text = "", Value = "" });

                foreach (var a in sStateName.Distinct().OrderBy(it => it.STATE_ID))
                {
                    list2.Add(new SelectListItem() { Text = a.STATE_NAME, Value = a.STATE_ID.ToString() });
                    System.Diagnostics.Debug.WriteLine("B = State Name :" + a.STATE_NAME  + " C = State ID :" + a.STATE_ID );

                }
                //Console.WriteLine(ListSatateName);
                System.Diagnostics.Debug.WriteLine("B = State Name :" + list2);
            }
            ViewBag.StateName = list2;
            
            string input = "\\\\adsvr";
            //string input = "\\\\server\\d$\\x\\y\\z\\AAA";
            string output = String.Format("http:{0}", input.Replace("\\d$\\x\\y", String.Empty).Replace("\\", "/"));

            ViewBag.output = output;

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(PTTMain.PTTMaintenanceList.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult NewPTTMaintenance()
        {
            List<SelectListItem> list2 = new List<SelectListItem>();
            List<SelectListItem> list3 = new List<SelectListItem>();
            using (Entities ctxData = new Entities())
            {

                var sStateName = (from d in ctxData.WV_STATE_MAST
                                  select d);

                list2.Add(new SelectListItem() { Text = "", Value = "" });

                foreach (var a in sStateName.Distinct().OrderBy(it => it.STATE_ID))
                {
                    list2.Add(new SelectListItem() { Text = a.STATE_NAME, Value = a.STATE_ID.ToString() });
                    //System.Diagnostics.Debug.WriteLine("B = State Name :" + a.STATE_NAME + " C = State ID :" + a.STATE_ID);

                }


                var queryRegion = (from d in ctxData.WV_REGION_MAST 
                                  select d);

                list3.Add(new SelectListItem() { Text = "", Value = "" });

                foreach (var a in queryRegion.Distinct().OrderBy(it => it.REGION_ID ))
                {
                    list3.Add(new SelectListItem() { Text = a.REGION_NAME , Value = a.REGION_ID .ToString() });
                   // System.Diagnostics.Debug.WriteLine("B = State Name :" + a.STATE_NAME + " C = State ID :" + a.STATE_ID);

                }
                //Console.WriteLine(ListSatateName);
                //System.Diagnostics.Debug.WriteLine("B = State Name :" + list2);
            }
            ViewBag.StateName = list2;
            ViewBag.RegionName = list3;

            return View();
        }

        [HttpPost]
        public ActionResult NewPTTMaintenance(PTTMaintenanceModel m)
        {
            bool success = true;
            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            bool selected = false;

            WebService._base.PTTMaintenance newPTTMain = new WebService._base.PTTMaintenance();
            //System.Diagnostics.Debug.WriteLine("State Name :" + m.RegionId);
            newPTTMain.PTT_ID= m.PTTId;
            newPTTMain.PTT_DESC = m.PTTDesc;
            newPTTMain.REGION_ID = m.RegionId;
            newPTTMain.COST_CENTRE = m.CostCentre;
            newPTTMain.STATE_CODE = m.StateCode;
            newPTTMain.STATE_NAME = m.StateName;

            
            success = myWebService.AddPTTMaintenance(newPTTMain);
            selected = true;

            if (ModelState.IsValid && selected)
            {
                if (success == true)
                    return RedirectToAction("NewSave");
                else
                    return RedirectToAction("NewSaveFail"); // store to db failed.
            }

            return View(m);
        }

        public ActionResult NewSave()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetDetails(string id)
        {
            string fileListStr = "";
            string dataStateName = "";
            string regionSelect ="";
           

            using (Entities ctxData = new Entities())
            {
                var query = (from q in ctxData.WV_PTT_MAST
                             where q.PTT_ID == id
                             select q).Single();

                var getStateCode = query.STATE_CODE;
                
                var queryStateCode = (from q in ctxData.WV_STATE_MAST
                                      where q.STATE_ID == getStateCode
                                      select new { q.STATE_NAME });

                foreach (var a in queryStateCode.Distinct())
                {
                    dataStateName = dataStateName + a.STATE_NAME;
                }

                string stateListName = "";
                var queryAllStateCode = (from q in ctxData.WV_STATE_MAST
                                         select new {q.STATE_NAME,q.STATE_ID});

                foreach (var b in queryAllStateCode.Distinct())
                {
                    stateListName = stateListName + b.STATE_ID  + ":  " + b.STATE_NAME + "|";
                }
                //System.Diagnostics.Debug.WriteLine("A :" + stateListName);


                //***********Region List***********
                var getRegion = query.REGION_ID;

                var queryRegionSelect = (from a in ctxData.WV_REGION_MAST
                                         where a.REGION_ID == getRegion
                                         select new { a.REGION_NAME });

                foreach (var b in queryRegionSelect)
                {
                    regionSelect = regionSelect + b.REGION_NAME;
                }

                var queryRegion = (from a in ctxData.WV_REGION_MAST
                                   select new { a.REGION_NAME, a.REGION_ID });
                string regionList ="";

                foreach (var b in queryRegion)
                {
                    regionList = regionList + b.REGION_ID + ": " + b.REGION_NAME + "|";
                }

                return Json(new
                {
                    Success = true,
                    PTTId = id,
                    PTTDesc = query.PTT_DESC,
                    RegionId = query.REGION_ID,
                    CostCentre = query.COST_CENTRE ,
                    StateCode = query.STATE_CODE,
                    StateName = dataStateName,
                    StateList = stateListName,
                    dregionList = regionList,
                    dregionSelect = regionSelect,

                    files_list = new
                    {
                        files = fileListStr
                    }
                }, JsonRequestBehavior.AllowGet); //
            }
        }

        [HttpPost]
        public ActionResult DeleteData(string targetPTTId)
        {
            bool success;

            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            success = myWebService.DeletePTTMaintenance(targetPTTId);

            return Json(new
            {
                Success = success
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateData(string PTTIdVal, string txtPTTDesc, string txtRegionId, string txtCostCentre, string txtStateName)
        {
            bool success = true;

            WebView.WebService._base myWebService;
            myWebService = new WebService._base();

            WebService._base.PTTMaintenance newPTTMain = new WebService._base.PTTMaintenance();
            newPTTMain.PTT_DESC = txtPTTDesc;
            newPTTMain.REGION_ID = txtRegionId;
            newPTTMain.COST_CENTRE = txtCostCentre;
            newPTTMain.STATE_CODE = txtStateName;
            success = myWebService.UpdatePTTMaintenance(newPTTMain, PTTIdVal);

            return Json(new
            {
                Success = success
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

source/WebView/Views/PTTMaintenance/List.cshtml
@model PagedList.IPagedList<WebView.WebService._base.PTTMaintenance>
@{
    ViewBag.Title = "List";
}

<script type="text/javascript">

    function GetDetailsCallBack(data) {
        document.getElementById("divDetails").style.display = "block";

        SetElement("txtPTTId", data.PTTId);
        SetElement("txtPTTDesc", data.PTTDesc);
        SetElement("txtRegionId", data.RegionId);
        SetElement("txtCostCentre", data.CostCentre);
        SetElement("txtStateName", data.StateName);
        SetElement("PTTIdVal", data.PTTId);
        document.getElementById("targetPTTId").value = data.PTTId;
        document.getElementById("btnClose").disabled = false;
        document.getElementById("txtPTTId").disabled = true;
    }

    function SaveUpdateCallBack(data) {
        document.getElementById("txtPTTDesc").readOnly = true;
        document.getElementById("txtRegionId").readOnly = true;
        document.getElementById("txtCostCentre").readOnly = true;
        document.getElementById("txtStateName").readOnly = true;
        document.getElementById("btnSave").disabled = false;

        if (data.Success == true) {
            alert("Successfully Updated.");
            document.getElementById("divDetails").style.display = "none";
            window.location.reload();
        }
    }

    jQuery(document).ready(function ($) {

        $("#rounded-corner tbody tr").bind("click", function () {
            var t = $(this).find("#gid").text();

            $("#divDetails").dialog("open");

            $.ajax({
                url: '@Url.Action("GetDetails", "PTTMaintenance")',
                type: "POST",
                dataType: "html",
                data: {
                    "id": t,
                    "random": Math.random()
                },
                beforeSend: function () { },
                success: function (data) {
                    var res = jQuery.parseJSON(data);

                    GetDetailsCallBack(res);
                    var stateNameList;
                    
                    stateNameList = res.StateList.split("|");

                    var dataListName = "<option selected value='" + res.StateCode + "'>" + res.StateName + "</option>";

                    for (i = 1; i < stateNameList.length; i++) {
                        if (stateNameList[i] != "") {

                            valueStateName = stateNameList[i].split(":");
                            dataListName += "<option value='" + valueStateName[0] + "'>" + valueStateName[1] + "</option>";
                            
                        }

                    }
                    $("#txtStateName").html(dataListName);


                    RegionList = res.dregionList.split("|");

                    var dataRegionList = "<option selected value='" + res.RegionId + "'>" + res.dregionSelect + "</option>";
                    for (i = 1; i < RegionList.length; i++) {
                        if (RegionList[i] != "") {

                            valueStateName = RegionList[i].split(":");
                            dataRegionList += "<option value='" + valueStateName[0] + "'>" + valueStateName[1] + "</option>";

                        }

                    }
                    $("#txtRegionId").html(dataRegionList);
                }
            });
        });

        var close = function () {
            $(this).dialog("close");
        }

        $("#divDetails").dialog({
            autoOpen: false,
            minHeight: 'auto',
            width: 700,
            modal: true,
            buttons: {
            },
            close: function () {
                //allFields.val("").removeClass("ui-state-error");
            }
        });

        $(function () {
            $('#btnSearch').click(function () {
                window.location = "List?searchKey=" + document.getElementById("searchKey").value; //Where List is the function in the controller.
            });

            $('#searchKey').change(function () {
                window.location = "List?searchKey=" + document.getElementById("searchKey").value; //Where List is the function in the controller.
            });

            $('#btnClose').click(function () {
                $("#divDetails").dialog("close");
            });

            $('#btnNewJob').click(function () {
                window.location = "NewPTTMaintenance";
            });

            $("#btnNewJob").button();
            $("#btnSearch").button();
            $("#btnClose").button();
            $("#btnDelete").button();
            $("#btnSave").button();

            $('#btnDelete').click(function () {
                var cmsg = confirm('Are you sure you want to Delete?');
                if (cmsg != 0) {
                    $.ajax({
                        url: "/PTTMaintenance/DeleteData",
                        type: "POST",
                        dataType: "html",
                        data: {
                            "targetPTTId": document.getElementById("targetPTTId").value,
                            "random": Math.random()
                        },
                        beforeSend: function () { },
                        success: function (data) {
                            var res = jQuery.parseJSON(data);

                            if (res.Success == true) {
                                alert("Deleted");
                                window.location.reload();
                            }
                            else {
                                alert("Delete failed.");
                            }
                        }
                    });
                }
            });
        });
    });

    function ShowIt() {
        document.getElementById("divLoading").style.visibility = "visible";
    }

    function HideIt() {
        document.getElementById("divLoading").style.visibility = "hidden";
    }

</script>

<br />
<h2>PTT Maintenance List</h2>
<div style="height:650px">
    <div>
        <table style="width:850px;">
            <tr>
                <td style="width:200px;"><input type="text" id="searchKey" name="searchKey"  value="@ViewBag.searchKey"/></td>
                <td><input type="button" value="Search" id="btnSearch" /></td>
                <td style="text-align:right"><input type="button" value="Add New" id="btnNewJob" /></td>
            </tr>
        </table>
    </div><br />
@if (Model.Count() > 0)
{
    <table id="rounded-corner" summary="PTTMaintenance List" width="850px">
        <thead>
            <tr>
                <th scope="col">PTT ID</th>
                <th scope="col">PTT Description</th>
                 <th scope="col">Region ID</th>       
                 <th scope="col">Cost Center</th>
                 <th scope="col">State Name</th>         
            </tr>
        </thead>
        <tbody>
        @foreach (var res in Model)
        {
            <tr class="odd">
                <td id="gid">@res.PTT_ID</td>
                <td>@res.PTT_DESC</td>
                <td>@res.REGION_ID</td>
                <td>@res.COST_CENTRE </td>
                <td>@res.STATE_NAME</td>                    
                @*<td>@Ajax.ActionLink("Details", "GetDetails", new { id = res.PTT_ID }, new AjaxOptions
               {
                   HttpMethod = "POST",
                   OnBegin = "ShowIt",
                   OnComplete = "HideIt",
                   UpdateTargetId = "divResultText",
                   OnSuccess = "GetDetailsCallBack"
               })</td>*@
            </tr>    
        }
        </tbody>
    </table>
    <div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of @Model.PageCount
        &nbsp;
        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("<<", "List", new { searchKey = "", page = 1 })
            @Html.Raw("&nbsp;");
            @Html.ActionLink("< Prev", "List", new { searchKey = "", page = Model.PageNumber - 1 })
        }
        else
        {

        }
        &nbsp;
        @if (Model.HasNextPage)
        {
            @Html.ActionLink("Next >", "List", new { searchKey = "", page = Model.PageNumber + 1 })
            @Html.Raw("&nbsp;");
            @Html.ActionLink(">>", "List", new { searchKey = "", page = Model.PageCount })
        }
        else
        {

        }<br /><b>Total @Model.TotalItemCount Record</b>
    </div>
}
else
{
        @:<br /><span style="font-size:12px;">No record found.</span> 
    }
    <br />
    <div id="divLoading" style="visibility:hidden"><img src="@Url.Content("~/Content/images/rel_interstitial_loading.gif")" alt="loading..." /></div>
    <div id="divResultText"></div>
    <br />
    <div id="divDetails" title="Details" style="padding-left:40px; padding-top:30px;">      
        <input type="hidden" id="targetPTTId" value="" />
        @using (Ajax.BeginForm("UpdateData", new AjaxOptions()
        {
            OnBegin = "ShowIt",
            OnComplete = "HideIt",
            OnSuccess = "SaveUpdateCallBack"
        }))
        {
        <div id="list-details" style="height:200px">
           <input type="hidden" id="PTTIdVal" name="PTTIdVal" />
            <table width="400px">
            <tr>
                    <td style="width:150px; background-color:#e8eef4">PTT ID</td>
                    <td><input type="text" id="txtPTTId" name="txtPTTId" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                                      
                </tr>
                <tr>
                    <td style="width:150px; background-color:#e8eef4">PTT Description</td>
                    <td><input type="text" id="txtPTTDesc" name="txtPTTDesc" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                                      
                </tr>
              <tr>
                    <td style="width:150px; background-color:#e8eef4">Region ID</td>
                    <td><select id="txtRegionId" name="txtRegionId">
                    </select></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                                      
                </tr>
                @***********************************************************************@
                <tr>
                    <td style="width:150px; background-color:White">Cost Center</td>
                    <td><input type="text" id="txtCostCentre" name="txtCostCentre" /></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                                      
                </tr>
                <tr>
                    <td style="width:150px; background-color:White">State Name</td>
                    <td><select id="txtStateName" name="txtStateName">
                    </select></td>
                    <td style=" border-top-color:White; border-bottom-color:White"></td>                                      
                </tr>
                @***********************************************************************@        
            </table>
            <br />            
            <div style="height:30px; margin-top:10px; margin-left:10px;">
                <input type="button" value="Delete" id="btnDelete" style="height:30px;width:80px; vertical-align:top;" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="Save" id="btnSave" style="height:30px;width:80px; vertical-align:top;" />
                <input type="button" value="Cancel" id="btnClose" style="height:30px;width:80px;" />
            </div>
        </div>
        }
        <br />
        <br />
    </div>
</div>
    

source/WebView/Views/PTTMaintenance/NewPTTMaintenance.cshtml
@model WebView.Models.PTTMaintenanceModel
           

@{
    //ViewBag.Title = "List";
    ViewBag.Title = "PTTMaintenance";
}
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(function () {
            $("#btnSave").button();
        });
    });
</script>
<br />
<h2>New PTT Maintenance</h2>
@using (Html.BeginForm("NewPTTMaintenance", "PTTMaintenance", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "Error. Please correct the errors and try again.");
    <table width="450px" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td>PTT ID</td>
            <td>
                @Html.TextBoxFor(m => m.PTTId, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.PTTId)
            </td>
        </tr>
        <tr>
            <td>PTT Description</td>
            <td>
                @Html.TextBoxFor(m => m.PTTDesc, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.PTTDesc)
            </td>
        </tr>
        <tr>
            <td>Region Id</td>
            <td>
                 @Html.DropDownListFor(m => m.RegionId, (IEnumerable<SelectListItem>)ViewBag.RegionName, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.RegionId)
            </td>
        </tr>
         <tr>
            <td>Cost Center</td>
            <td>
                @Html.TextBoxFor(m => m.CostCentre  , new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.CostCentre )
            </td>
        </tr>
             <tr>
            <td>State Name</td>
            <td>
               @Html.DropDownListFor(m => m.StateCode, (IEnumerable<SelectListItem>)ViewBag.StateName, new { style = "width:200px;" })
            </td>
        </tr>

        @*<tr>
            <td>Cost Centre</td>
            <td>
                @Html.TextBoxFor(m => m.CostCentre, new { style = "width:200px;" })
                @Html.ValidationMessageFor(m => m.CostCentre)
            </td>
        </tr>*@              
    </table>
    <p>
        <input type="submit" value="Save" id="btnSave" />
    </p>                                                                                 
}

source/WebView/Views/PTTMaintenance/NewSave.cshtml
@{
    ViewBag.Title = "NewSave";
}

<h2>Status</h2>
<div style="height:400px">
New PTT Maintenance has been created.
</div>